version: '3.8'
services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=http://0.0.0.0:9090'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: '1000'
    ports:
      - '3000:3000'
    volumes:
      - ./monitoring/grafana/data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

  rust-app:
    container_name: rust-app
    build:
      context: .
      dockerfile: Docker/rust.dockerfile
    ports:
      - '80:8181'
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: postgres
    hostname: postgres
    build:
      context: .
      dockerfile: Docker/postgres.dockerfile
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
