apiVersion: "v1"
kind: "List"
items:
  - apiVersion: "v1"
    kind: "Service"
    metadata:
      annotations: {}
      labels: {}
      name: "landing-form"
    spec:
      selector:
        app: "landing-form"
      type: LoadBalancer
      ports:
        - name: http
          port: 8181
          targetPort: 8181
          nodePort: 32000
          protocol: TCP
  - apiVersion: "apps/v1"
    kind: "Deployment"
    metadata:
      labels:
        app: "landing-form"
      name: "landing-form"
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: "landing-form"
      template:
        metadata:
          labels:
            app: "landing-form"
        spec:
          containers:
            - image: "landing-form"
              imagePullPolicy: "Never"
              name: "landing-form"
              resources:
                limits:
                  cpu: 500m
                requests:
                  cpu: 200m
              ports:
                - protocol: TCP
                  containerPort: 8181